### ISSUE TITLE
Do you have this problem in  code and how to solve it?

### ISSUE THREAD

**Issue by zhonghuaxiaoxiaochen** [MADONOKOUKI/Block-wise-Scrambled-Image-Recognition#4]
Traceback (most recent call last):
  File "E:\Encode\Anaconda\envs\encrypted_image\lib\site-packages\PIL\Image.py", line 2645, in fromarray
    mode, rawmode = _fromarray_typemap[typekey]
**KeyError: ((1, 1, 3, 4), '|u1')**
  
  im = Image.fromarray(np.uint8(cm.gist_earth(data[0,:,:,:],bytes=True))*255)
  File "E:\Encode\Anaconda\envs\encrypted_image\lib\site-packages\PIL\Image.py", line 2647, in fromarray
    raise TypeError("Cannot handle this data type")
TypeError: Cannot handle this data type

**Comment by MADONOKOUKI** [comment]
I had a similar problem, but I can solve it by checking the data type.

**Comment by zhonghuaxiaoxiaochen** [comment]
How does it work exactly? Thank you.

**Comment by MADONOKOUKI** [comment]
Sorry I did not remember about it. Did you debug the code?

**Comment by zhonghuaxiaoxiaochen** [comment]
I've debugged the code, but it didn't succeed. I wonder if it's convenient for you to help me again,Thank you very much
