### ISSUE TITLE
Why use ShakePyramidNet to classify，instead of other network，such as resnet ？

### ISSUE THREAD

**Issue by HuangZuShu** [MADONOKOUKI/Block-wise-Scrambled-Image-Recognition#5]
Dear author，
The network is a little large. Whther it is ok to compare with you in smaller network, such as resnet.
Your method and our method is the same as resnet-18.

**Comment by MADONOKOUKI** [comment]
This is no problem to use resnet-18. We use large network in order to validate on large deep network
(I'm huge sorry of the delay, need to set some notification to my mail account...)
